language: java
sudo: false
script: mvn install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  file: "/home/travis/.m2/repository/ch/bbw/je/ConsoleCalculator/0.0.1-SNAPSHOT/ConsoleCalculator-0.0.1-SNAPSHOT.jar"
  on:
    repo: Nexterbyby/ConsoleCalculator