language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file: "/home/travis/.m2/repository/ch/bbw/je/ConsoleCalculator/1.0.0/ConsoleCalculator-1.0.0.jar"
  on:
    repo: Nexterbyby/ConsoleCalculator
    tags: true